version: '3'
services:
  db:
      build: ./mysql
      platform: linux/x86_64
      command: --default-authentication-plugin=mysql_native_password
      volumes:
        - db-store:/var/lib/mysql

  web:
    image: nginx:1.21.3-alpine
    ports:
      - 8000:8000
    volumes:
      - ./src:/code
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
    working_dir: /code
    depends_on:
      - app

  app:
    build: ./python
    command: uwsgi --socket :8001 --module shopify_mock.wsgi --py-autoreload 1 --logto /tmp/tmp.log
    volumes:
      - ./src:/code
    expose:
      - "8001"
    depends_on:
      - db

volumes:
  db-store: